/*
 * 		DatesPeriodPanel.java
 *   Copyright (C) 2016  Adrián E. Córdoba [software.asia@gmail.com]
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * 		DatesPeriodPanel.java
 *  Adrián E. Córdoba [software.asia@gmail.com] 		Jul 4, 2017
 */
package ar.com.adriancordoba.derqui.app.gui.derquisystemsmanager.derquisystemsmanagerfrontend.windows.dialogs;

import java.util.Calendar;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Adrián E. Córdoba [software.asia@gmail.com]
 */
public class DatesPeriodPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatesPeriodPanel
     */
    public DatesPeriodPanel() {
        createComboBoxModels();
        initComponents();

        fillDayComboBoxes();
        fillMonthComboBoxes();
        fillYearComboBoxes();
        setCurrentDateComboBoxes();
    }

    private void createComboBoxModels() {
        fromDayComboBoxModel = new DefaultComboBoxModel<>();
        toDayComboBoxModel = new DefaultComboBoxModel<>();
        fromMonthComboBoxModel = new DefaultComboBoxModel<>();
        toMonthComboBoxModel = new DefaultComboBoxModel<>();
        fromYearComboBoxModel = new DefaultComboBoxModel<>();
        toYearComboBoxModel = new DefaultComboBoxModel<>();
    }

    private void fillDayComboBoxes() {
        for (int i = 1; i <= 31; i++) {
            fromDayComboBoxModel.addElement(String.valueOf(i));
            toDayComboBoxModel.addElement(String.valueOf(i));
        }
    }

    private void fillMonthComboBoxes() {
        for (int i = 1; i <= 12; i++) {
            String month = bundle.getString("DatesPeriodPanel.MonthComboBoxes.month" + i);
            fromMonthComboBoxModel.addElement(month);
            toMonthComboBoxModel.addElement(month);
        }
    }

    private void fillYearComboBoxes() {
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = 2016; i <= currentYear; i++) {
            fromYearComboBoxModel.addElement(String.valueOf(i));
            toYearComboBoxModel.addElement(String.valueOf(i));
        }
        fromYearComboBoxModel.setSelectedItem(String.valueOf(currentYear));
    }

    private void setCurrentDateComboBoxes() {
        int currentDay = Calendar.getInstance().get(Calendar.DAY_OF_MONTH);
        int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);

        toDayComboBox.setSelectedItem(String.valueOf(currentDay));
        toMonthComboBox.setSelectedItem(bundle.getString("DatesPeriodPanel.MonthComboBoxes.month" + (currentMonth + 1)));
        toYearComboBox.setSelectedItem(String.valueOf(currentYear));
    }

    public int getFromDay() {
        return fromDayComboBox.getSelectedIndex() + 1;
    }

    public int getFromMonth() {
        return fromMonthComboBox.getSelectedIndex() + 1;
    }

    public int getFromYear() {
        return Integer.parseInt((String) fromYearComboBox.getSelectedItem());
    }

    public int getToDay() {
        return toDayComboBox.getSelectedIndex() + 1;
    }

    public int getToMonth() {
        return toMonthComboBox.getSelectedIndex() + 1;
    }

    public int getToYear() {
        return Integer.parseInt((String) toYearComboBox.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        fromDayComboBox = new javax.swing.JComboBox<>();
        fromMonthComboBox = new javax.swing.JComboBox<>();
        fromYearComboBox = new javax.swing.JComboBox<>();
        toDayComboBox = new javax.swing.JComboBox<>();
        toMonthComboBox = new javax.swing.JComboBox<>();
        toYearComboBox = new javax.swing.JComboBox<>();

        fromLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/MainFrameBundle"); // NOI18N
        fromLabel.setText(bundle.getString("DatesPeriodPanel.fromLabel.text")); // NOI18N

        toLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        toLabel.setText(bundle.getString("DatesPeriodPanel.toLabel.text")); // NOI18N

        fromDayComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fromDayComboBox.setModel(fromDayComboBoxModel);

        fromMonthComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fromMonthComboBox.setModel(fromMonthComboBoxModel);

        fromYearComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fromYearComboBox.setModel(fromYearComboBoxModel);

        toDayComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        toDayComboBox.setModel(toDayComboBoxModel);

        toMonthComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        toMonthComboBox.setModel(toMonthComboBoxModel);

        toYearComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        toYearComboBox.setModel(toYearComboBoxModel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromLabel)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromDayComboBox, 0, 51, Short.MAX_VALUE)
                    .addComponent(toDayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromMonthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toMonthComboBox, 0, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromYearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toYearComboBox, 0, 71, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(fromDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLabel)
                    .addComponent(toDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fromDayComboBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JComboBox<String> fromMonthComboBox;
    private javax.swing.JComboBox<String> fromYearComboBox;
    private javax.swing.JComboBox<String> toDayComboBox;
    private javax.swing.JLabel toLabel;
    private javax.swing.JComboBox<String> toMonthComboBox;
    private javax.swing.JComboBox<String> toYearComboBox;
    // End of variables declaration//GEN-END:variables

    private DefaultComboBoxModel<String> fromDayComboBoxModel;
    private DefaultComboBoxModel<String> toDayComboBoxModel;
    private DefaultComboBoxModel<String> fromMonthComboBoxModel;
    private DefaultComboBoxModel<String> toMonthComboBoxModel;
    private DefaultComboBoxModel<String> fromYearComboBoxModel;
    private DefaultComboBoxModel<String> toYearComboBoxModel;

    private ResourceBundle bundle = ResourceBundle.getBundle("i18n/MainFrameBundle"); // NOI18N
    private static final Logger logger = LogManager.getLogger(DatesPeriodPanel.class);
}
