/*
 * 		DateSelectionPanel.java
 *   Copyright (C) 2016  Adrián E. Córdoba [software.asia@gmail.com]
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * 		DateSelectionPanel.java
 *  Adrián E. Córdoba [software.asia@gmail.com] 		Jul 7, 2017
 */
package ar.com.adriancordoba.derqui.app.gui.derquisystemsmanager.derquisystemsmanagerfrontend.windows.dialogs;

import java.util.Calendar;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Adrián E. Córdoba [software.asia@gmail.com]
 */
public class DateSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatePanel
     */
    public DateSelectionPanel() {
        createComboBoxModels();
        initComponents();

        fillDayComboBoxe();
        fillMonthComboBoxe();
        fillYearComboBoxe();
        setCurrentDateComboBoxe();
    }

    private void createComboBoxModels() {
        dayComboBoxModel = new DefaultComboBoxModel<>();
        monthComboBoxModel = new DefaultComboBoxModel<>();
        yearComboBoxModel = new DefaultComboBoxModel<>();
    }

    private void fillDayComboBoxe() {
        for (int i = 1; i <= 31; i++)
            dayComboBoxModel.addElement(String.valueOf(i));
    }

    private void fillMonthComboBoxe() {
        for (int i = 1; i <= 12; i++)
            monthComboBoxModel.addElement(bundle.getString("DatesPeriodPanel.MonthComboBoxes.month" + i));
    }

    private void fillYearComboBoxe() {
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = 2016; i <= currentYear; i++)
            yearComboBoxModel.addElement(String.valueOf(i));
    }

    private void setCurrentDateComboBoxe() {
        int currentDay = Calendar.getInstance().get(Calendar.DAY_OF_MONTH);
        int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);

        dayComboBox.setSelectedItem(String.valueOf(currentDay));
        monthComboBox.setSelectedItem(bundle.getString("DatesPeriodPanel.MonthComboBoxes.month" + (currentMonth + 1)));
        yearComboBox.setSelectedItem(String.valueOf(currentYear));
    }

    public int getDay() {
        return dayComboBox.getSelectedIndex() + 1;
    }

    public int getMonth() {
        return monthComboBox.getSelectedIndex() + 1;
    }

    public int getYear() {
        return Integer.parseInt((String) yearComboBox.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        dayComboBox = new javax.swing.JComboBox<>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();

        dateLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/MainFrameBundle"); // NOI18N
        dateLabel.setText(bundle.getString("DateSelectionPanel.dateLabel.text")); // NOI18N

        dayComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dayComboBox.setModel(dayComboBoxModel);

        monthComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        monthComboBox.setModel(monthComboBoxModel);

        yearComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        yearComboBox.setModel(yearComboBoxModel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> dayComboBox;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables

    private DefaultComboBoxModel<String> dayComboBoxModel;
    private DefaultComboBoxModel<String> monthComboBoxModel;
    private DefaultComboBoxModel<String> yearComboBoxModel;

    private ResourceBundle bundle = ResourceBundle.getBundle("i18n/MainFrameBundle"); // NOI18N
    private static final Logger logger = LogManager.getLogger(DateSelectionPanel.class);
}
