/*
 * 		SearchPeoplePanel.java
 *   Copyright (C) 2016  Adrián E. Córdoba [software.asia@gmail.com]
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * 		SearchPeoplePanel.java
 *  Adrián E. Córdoba [software.asia@gmail.com] 		Aug 6, 2016
 */
package ar.com.adriancordoba.derqui.app.gui.derquisystemsmanager.derquisystemsmanagerfrontend.windows.dialogs;

import ar.com.adriancordoba.derqui.app.console.derquisystemsmanager.derquisystemsmanagerdataaccess.model.person.IdentificationType;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Adrián E. Córdoba [software.asia@gmail.com]
 */
public class SearchPeoplePanel extends javax.swing.JPanel {
    private static ResourceBundle bundle = ResourceBundle.getBundle("i18n/PeopleInternalFrameBundle"); // NOI18N

    /**
     * Creates new form SearchPeoplePanel
     */
    public SearchPeoplePanel(DefaultComboBoxModel<IdentificationType> identificationTypeComboBoxModel) {
        this.identificationTypeComboBoxModel = identificationTypeComboBoxModel;
        initComponents();
        identificationTypeComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        identificationPanel = new javax.swing.JPanel();
        identificationTypeComboBox = new javax.swing.JComboBox<>();
        identificationNumberLabel = new javax.swing.JLabel();
        identificationNumberTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        middleNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();

        firstNameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/PeopleInternalFrameBundle"); // NOI18N
        firstNameLabel.setText(bundle.getString("PeopleInternalFrame.firstNameLabel.text")); // NOI18N

        middleNameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        middleNameLabel.setText(bundle.getString("PeopleInternalFrame.middleNameLabel.text")); // NOI18N

        lastNameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lastNameLabel.setText(bundle.getString("PeopleInternalFrame.lastNameLabel.text")); // NOI18N

        identificationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("PeopleInternalFrame.PersonPanel.IdentificationPanel.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        identificationTypeComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        identificationTypeComboBox.setModel(identificationTypeComboBoxModel);

        identificationNumberLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        identificationNumberLabel.setText(bundle.getString("PeopleInternalFrame.identificationNumberLabel.text")); // NOI18N

        identificationNumberTextField.setText(bundle.getString("SearchPeoplePanel.identificationNumberTextField.text")); // NOI18N

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addComponent(identificationNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(identificationNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(identificationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificationNumberLabel)
                    .addComponent(identificationNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstNameTextField.setText(bundle.getString("SearchPeoplePanel.firstNameTextField.text")); // NOI18N

        middleNameTextField.setText(bundle.getString("SearchPeoplePanel.middleNameTextField.text")); // NOI18N

        lastNameTextField.setText(bundle.getString("SearchPeoplePanel.lastNameTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lastNameLabel)
                            .addGap(26, 26, 26)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(middleNameLabel)
                                .addComponent(firstNameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameTextField)
                                .addComponent(middleNameTextField)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleNameLabel)
                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(identificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getFirstName() {
        return firstNameTextField.getText();
    }

    public int getIdentificationNumber() throws Exception {
        int identificationNumber = 0;
        if (!identificationNumberTextField.getText().isEmpty())
            identificationNumber = Integer.parseInt(identificationNumberTextField.getText());
        return identificationNumber;
    }

    public int getIdentificationType() {
        return ((IdentificationType) identificationTypeComboBox.getSelectedItem()).getId();
    }

    public String getLastName() {
        return lastNameTextField.getText();
    }

    public String getMiddleName() {
        return middleNameTextField.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel identificationNumberLabel;
    private javax.swing.JTextField identificationNumberTextField;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JComboBox<IdentificationType> identificationTypeComboBox;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField middleNameTextField;
    // End of variables declaration//GEN-END:variables

    private DefaultComboBoxModel<IdentificationType> identificationTypeComboBoxModel;
}
